#/************************************************************************ *
#* Goma - Multiphysics finite element software                             *
#* Sandia National Laboratories                                            *
#*                                                                         *
#* Copyright (c) 2014 Sandia Corporation.                                  *
#*                                                                         *
#* Under the terms of Contract DE-AC04-94AL85000 with Sandia Corporation,  *
#* the U.S. Government retains certain rights in this software.            *
#*                                                                         *
#* This software is distributed under the GNU General Public License.      *
#\************************************************************************/

# Makefile for brk/fix, a tool to add nodes to an EXODUS FE database
#
# Note: Usually you should use the Makefile automatically generated by
#       running configure. This one is for quick and dirty development
#	work.
#
            SHELL = /bin/sh

#            PURE = purify -cache-dir="/tmp"
               RM = rm -f

               CC = gcc
#	        CC =  /home/sntools/extras/mpi/mpich-1.2.7p1-gcc-3.4.6-32Bit/bin/mpicc

#          ACCESS = /usr/local/eng_sci/struct/current
#           ACCESS = /home/goma/production/linux/SEAMS_2006-03-16-32-GCC
           ACCESS = /projects/seacas/current

             _INC = -I. -I$(ACCESS)/inc

         INCLUDES = $(_INC) -I.

      CDEBUGFLAGS = -g -Wall 

  COPTIMIZEFLAGS = -O -Wall

#          DEFINES = -DHAVE_CONFIG_H=1 -DPOTATO_CHIP_DIET
          DEFINES = -DHAVE_CONFIG_H=1

           CFLAGS = $(CDEBUGFLAGS) $(COPTIMIZEFLAGS) $(CCOPTIONS) $(DEFINES) $(INCLUDES)
             _LIB = -L$(ACCESS)/lib

        LIB_CHACO = -lchaco

       LIB_NETCDF = -lnetcdf -lhdf5_hl -lhdf5

       LIB_EXODUS = -lexoIIv2c

          LIB_SYS = -lm -lz# -lccmalloc -ldl

             LIBS = $(_LIB) $(LIB_EXODUS) $(LIB_NETCDF) $(LIB_CHACO) $(LIB_SYS)

            FOBJS = fix.o rd_exo.o wr_exo.o rd_dpi.o wr_dpi.o utils.o \
		    aalloc.o eh.o bbb.o exo_utils.o

             OBJS = brk.o rd_exo.o wr_exo.o rd_in.o wr_graph_file.o mk_dm.o \
                    wr_coords.o ppi.o sam_perea.o wr_dpi.o \
		    utils.o aalloc.o eh.o exo_utils.o exo_conn.o emuck.o \
                    rd_dpi.o

all: brk fix

tags:
	find . -name "*.[c]" -exec etags -a '{}' \;

fix: $(FOBJS)
	$(RM) $@;\
	$(CC) $(COPTIMIZEFLAGS) -o $@ $(FOBJS) $(LIBS)

brk: $(OBJS)
	$(RM) $@;\
	$(PURE) $(CC) $(COPTIMIZEFLAGS) -o $@ $(OBJS) $(LIBS)

clean:
	-rm -f *.o *~ tmp* core junk* *.BAK *%

realclean:
	-rm -f *.fem *.pcon *.psplot *.o *~ tmp* junk* *.BAK *%
